### ISSUE TITLE
Documents, current issues

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/pancancer-info#1]
Hi,
Will create notes here during our meeting, we can decide how to split this up in a meeting.

* ~~architecture-overview will need images with a description of the various components that we have, we can steal slides from the slide-pack that Brian had~~

These are targeted at cloud shepherds
* ~~we will need to split up guide into components, 1) how to build a launcher host, how to build up a box to an image from scratch on AWS 2) how to snapshot it on Amazon 2a) Cloud-specific notes on how to do the previous steps on other clouds  3) how to use bindle to startup from a snapshot in an academic cloud   4) how to setup youxia in both Amazon and the academic cloud environment~~
* Fill out the vCloud portion of the document on imaging instances https://github.com/ICGC-TCGA-PanCancer/pancancer-info/blob/develop/docs/image_instance.md
* Fill out the vCloud portion of the document on spinning up from a pre-created image https://github.com/ICGC-TCGA-PanCancer/pancancer-info/blob/develop/docs/instance_from_image_with_bindle.md

* Install docs should refer to tar.gz releases where possible rather than git checkouts as a parallel to built jar releases for Java code on artifactory (future, apt packages)

**Comment by a8wright** [comment]
I added information on those two docs for vCloud
